_target_: src.models.segmentation_module.SegmentationModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.deeplabv3_moblenet_v3_large.DeeplabV3
  num_classes: 19

# compile model for faster training with pytorch 2.0
compile: false
